/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class base62_Base62JNI */

#ifndef _Included_base62_Base62JNI
#define _Included_base62_Base62JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     base62_Base62JNI
 * Method:    encode
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_base62_Base62JNI_encode__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     base62_Base62JNI
 * Method:    encode
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_base62_Base62JNI_encode__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     base62_Base62JNI
 * Method:    encode
 * Signature: (DI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_base62_Base62JNI_encode__DI
  (JNIEnv *, jobject, jdouble, jint);

/*
 * Class:     base62_Base62JNI
 * Method:    encode
 * Signature: (FI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_base62_Base62JNI_encode__FI
  (JNIEnv *, jobject, jfloat, jint);

/*
 * Class:     base62_Base62JNI
 * Method:    decode
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_base62_Base62JNI_decode
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     base62_Base62JNI
 * Method:    decodeD
 * Signature: (Ljava/lang/String;I)D
 */
JNIEXPORT jdouble JNICALL Java_base62_Base62JNI_decodeD
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     base62_Base62JNI
 * Method:    decodeF
 * Signature: (Ljava/lang/String;I)F
 */
JNIEXPORT jfloat JNICALL Java_base62_Base62JNI_decodeF
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
